"""Reasoner validation of the Phase 1 filter.

The claim under test is the paper's deployment advice: that a practitioner may trust
an LLM-drafted definition once it has passed the Phase 1 satisfiability filter. The
the objection is that passing is nearly uninformative, because the checker sees
one definition in isolation while the surrounding ontology never constrains it. So the
question is:

    when the filter accepts a definition, does an OWL DL reasoner still accept it
    once that definition is asserted into an ontology that actually has constraints?

The quantity that decides whether the deployment claim survives is the FALSE-PASS
RATE: filter-accepted definitions that a reasoner finds unsatisfiable.

Three arms plus a control, differing only in what constrains the ontology:

  control  the study ontologies as they are. All seven declare zero disjointness, so
           this measures what the procedure yields when nothing can be contradicted.
           It is the null against which the other arms are read, and it is evidence
           for the sparse-constraint point rather than a result about models.
  arm_a    DBpedia with its own 27 asserted owl:disjointWith axioms. The only arm
           where an unsatisfiability verdict is licensed by the source ontology.
  arm_b    DBpedia plus the 170,144 pruned disjointness axioms released by Crum et al.
           (KBC-LM'24, arXiv 2410.03235). Those axioms are themselves LLM-generated by
           models of our size class, at a reported ~0.75 accuracy, so this arm measures
           consistency against a published enrichment, NOT correctness.
  arm_c    manual curation; the author's labels. Not computed here.

Arms A and B need definitions of DBpedia classes, which the study has not generated.
Until a Phase 1 run over DBpedia concepts exists they are reported as NOT RUN, with
the reason stated, rather than approximated by asserting anatomy definitions into
DBpedia --- classes that do not exist there would be created unconstrained and every
one would come back satisfiable, which would be an artefact and not a finding.

Translation fidelity is the main risk and is handled by refusing to guess: only the
conjunction-of-named-classes fragment is translated (see fol_to_owl.py), and the
not-translatable count is reported per cause instead of being hidden in a denominator.

Compute: CPU only, local. No LLM calls, no network. HermiT ships with owlready2.

Run:
    python src/analysis/reasoner_validation.py
    python src/analysis/reasoner_validation.py reasoner.arm=control reasoner.limit=200
"""

from __future__ import annotations

import csv
import glob
import json
import shutil
import sys
import tempfile
from collections import Counter, defaultdict
from pathlib import Path

import hydra
from omegaconf import DictConfig

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))
csv.field_size_limit(10 ** 9)

# Arm B asserts into DBpedia enriched with 170,144 disjointness axioms (144,611 of
# them over the first 200 classes alone). owlready2 walks that graph recursively and
# hits Python's default 1,000-frame limit long before the reasoner is even called,
# which surfaces as RecursionError and is recorded as a per-definition error -- the
# definition then vanishes from the denominator instead of being scored.
sys.setrecursionlimit(100000)

from src.analysis.fol_to_owl import classify_definition  # noqa: E402

def clopper_pearson(successes: int, trials: int, conf: float = 0.95) -> tuple[float, float]:
    """Exact binomial interval. Two-sided, as reported everywhere else in the paper."""
    if trials == 0:
        return (float("nan"), float("nan"))
    try:
        from scipy.stats import beta
    except ImportError:
        return (float("nan"), float("nan"))
    alpha = 1.0 - conf
    lower = 0.0 if successes == 0 else beta.ppf(alpha / 2, successes, trials - successes + 1)
    upper = 1.0 if successes == trials else beta.ppf(1 - alpha / 2, successes + 1, trials - successes)
    return (float(lower), float(upper))

def load_filter_accepted(cfg: DictConfig, root: Path) -> list[dict]:
    """Every stored definition the Phase 1 filter accepted, with its translation.

    "Accepted" means the filter did not report a contradiction. A definition the
    filter already rejected cannot be a false pass, so it is out of scope here.
    """
    rows: list[dict] = []
    for pattern in cfg.reasoner.results_dirs:  # noqa: (see results_dirs in conf)
        for path in sorted((root / pattern).glob("**/phase1_results.csv")):
            for row in csv.DictReader(open(path, newline="", errors="replace")):
                contradiction = str(row.get("contradiction", "")).strip().lower()
                if contradiction in ("1", "true", "yes"):
                    continue
                classes, reason = classify_definition(row.get("fol_block") or "")
                rows.append({
                    "ontology": (row.get("ontology") or "").strip(),
                    "model": (row.get("llm_model") or "").strip(),
                    "strategy": (row.get("strategy") or "").strip(),
                    "concept_label": (row.get("concept_label") or "").strip(),
                    "concept_iri": (row.get("concept_iri") or "").strip(),
                    "classes": classes,
                    "reason": reason,
                })
    return rows

def _reason_over(ontology_path: Path, definitions: list[dict],
                 timeout_s: int) -> dict[tuple[str, str, str], str]:
    """Assert each definition as EquivalentTo and ask HermiT which classes survive.

    Returns a verdict per DEFINITION, keyed on (model, strategy, concept_label).
    Keying on the label alone collapsed six models and four strategies into one entry
    per concept -- 61 definitions became 30 verdicts, and the 31 discarded were
    invisible because the error count stayed zero.

    Each definition is asserted into its OWN copy of the ontology. That is expensive
    and it is deliberate. Two cheaper variants were tried and both fail completely:
    sharing one world lets a single malformed intersection corrupt the store so that
    every later definition fails serialisation, and loading the same file URI
    repeatedly collides in owlready2's global registry. The per-definition copy is
    doing real work, not just tidiness.

    The cost is that ontologies too large to copy per definition -- AGROVOC at 1.2 GB,
    MeSH at 842 MB -- are excluded, and the exclusion is reported rather than hidden.
    """
    import owlready2

    verdicts: dict[tuple[str, str, str], str] = {}
    errors: list[tuple[str, str]] = []
    for definition in definitions:
        workdir = Path(tempfile.mkdtemp(prefix="reasoner_"))
        try:
            local = workdir / ontology_path.name
            shutil.copy(ontology_path, local)
            world = owlready2.World()
            onto = world.get_ontology(local.as_uri()).load()

            with onto:
                # The target must be a CLASS. `search_one(label=...)` can return an
                # object property (DBpedia puns freely: `country` is both), and
                # appending to a property's equivalent_to raises
                # "issubclass() arg 1 must be a class" -- recorded as an error, so the
                # definition leaves the denominator instead of being scored.
                target = onto.search_one(label=definition["concept_label"])
                if not (isinstance(target, owlready2.ThingClass)
                        and not isinstance(target, owlready2.PropertyClass)):
                    target = owlready2.types.new_class(
                        _safe_name(definition["concept_label"]), (owlready2.Thing,))
                conjuncts = [_get_or_make_class(onto, name) for name in definition["classes"]]
                expression = conjuncts[0]
                for extra in conjuncts[1:]:
                    expression = expression & extra
                target.equivalent_to.append(expression)

            try:
                with onto:
                    owlready2.sync_reasoner(world, debug=0)
                unsat = _is_unsatisfiable(world, target)
                verdicts[_key(definition)] = "unsatisfiable" if unsat else "satisfiable"
            except owlready2.OwlReadyInconsistentOntologyError:
                verdicts[_key(definition)] = "inconsistent"
            except Exception as exc:
                verdicts[_key(definition)] = f"error:{type(exc).__name__}"
                errors.append((definition["concept_label"], f"{type(exc).__name__}: {exc}"[:160]))
        except Exception as exc:
            verdicts[_key(definition)] = f"setup_error:{type(exc).__name__}"
            errors.append((definition["concept_label"], f"setup {type(exc).__name__}: {exc}"[:160]))
        finally:
            shutil.rmtree(workdir, ignore_errors=True)
    if errors:
        print(f"\n  first errors ({len(errors)} total):")
        for label, message in errors[:4]:
            print(f"    {label[:32]:34s} {message}")
    return verdicts

def _is_unsatisfiable(world, target) -> bool:
    """Did the reasoner find the asserted class unsatisfiable?

    `world.inconsistent_classes()` is a GENERATOR that materialises every entity it
    walks past. On DBpedia enriched with 170,144 disjointness axioms, some entity has
    a non-class among its stored superclasses (punning at the storid level), and
    materialising it raises `TypeError: issubclass() arg 1 must be a class` -- before
    the generator ever reaches our target. Every definition then scored as an error
    and left the denominator, which is how a 4-definition arm reported 3 errors.

    The primary test touches only the target: `sync_reasoner` marks an unsatisfiable
    class by making it equivalent to Nothing. The generator is kept as a fallback and
    iterated defensively, so one poisoned entity cannot discard a whole run.
    """
    import owlready2
    try:
        if owlready2.Nothing in list(getattr(target, "equivalent_to", [])):
            return True
    except Exception:
        pass
    try:
        for cls in world.inconsistent_classes():
            if cls is target:
                return True
    except TypeError:
        # Poisoned entity in the walk; the Nothing test above is authoritative.
        pass
    return False

def _key(definition: dict) -> tuple[str, str, str]:
    """Identity of a definition: the same concept defined by a different model or
    under a different strategy is a different observation."""
    return (definition.get("model", ""), definition.get("strategy", ""),
            definition.get("concept_label", ""))

def _safe_name(label: str) -> str:
    return "".join(ch if ch.isalnum() else "_" for ch in label) or "Concept"

def _get_or_make_class(onto, name: str):
    """Resolve a conjunct name to a CLASS, never to a property.

    DBpedia puns: `country` is both an object property and a class name, and
    `search_one(iri=...)` returns whichever it finds first. Intersecting a property
    raises `unsupported operand type(s) for &`, which the caller records as an error
    -- so the definition is silently dropped from the denominator rather than scored.
    Requiring an actual class, and minting a fresh one otherwise, keeps the definition
    in the analysis and makes the assertion mean what it says.
    """
    import owlready2
    existing = onto.search_one(iri=f"*{name}")
    if (existing is not None
            and isinstance(existing, owlready2.ThingClass)
            and not isinstance(existing, owlready2.PropertyClass)):
        return existing
    return owlready2.types.new_class(_safe_name(name), (owlready2.Thing,))

@hydra.main(version_base=None, config_path="../../conf", config_name="analysis")
def main(cfg: DictConfig) -> None:
    root = Path(hydra.utils.get_original_cwd())
    arm = cfg.reasoner.arm
    out_dir = root / cfg.paths.out_dir
    out_dir.mkdir(parents=True, exist_ok=True)

    rows = load_filter_accepted(cfg, root)
    translatable = [r for r in rows if r["classes"]]
    reasons = Counter(r["reason"] for r in rows)

    print(f"arm: {arm}")
    print(f"filter-accepted definitions : {len(rows)}")
    print(f"translatable to OWL         : {len(translatable)} "
          f"({100 * len(translatable) / max(len(rows), 1):.1f}%)")
    print("\nnot translatable, by cause (published, not hidden):")
    for reason, count in reasons.most_common():
        if reason == "ok":
            continue
        print(f"  {reason:26s} {count:5d}  {100 * count / max(len(rows),1):5.1f}%")

    # An arm may only run over ontologies whose own concepts were defined by the
    # models. Asserting a definition of some other ontology's concept would create
    # unconstrained classes and return a vacuous 0% false-pass rate -- an artefact.
    # Arms A and B were gated on this until 2026-09-01, when Phase 1 over IDO and
    # ENVO supplied the substrate: those two declare 312 and 135 disjointness axioms
    # respectively, against zero in every ontology of the submitted study.
    allowed = set(cfg.reasoner.arm_ontologies.get(arm, []))
    if allowed:
        before = len(translatable)
        translatable = [r for r in translatable if r["ontology"] in allowed]
        print(f"\narm '{arm}' restricted to {sorted(allowed)}: "
              f"{len(translatable)} of {before} translatable definitions")
        if not translatable:
            print(f"NOT RUN: no definitions exist for {sorted(allowed)}. "
                  f"Phase 1 over those concepts is the prerequisite.")
            return

    by_ontology: dict[str, list[dict]] = defaultdict(list)
    for row in translatable:
        by_ontology[row["ontology"]].append(row)

    limit = int(cfg.reasoner.limit)
    summary = []
    for ontology, definitions in sorted(by_ontology.items()):
        # An arm may assert into a different ontology than the definitions came from
        # (arm B: DBpedia definitions into the Crum-enriched DBpedia). Without this
        # the arm would silently reason over the unenriched file and report a false
        # 0% against constraints it never loaded.
        override = (cfg.reasoner.get("arm_file_override", {}) or {}).get(arm, {}) or {}
        file_key = override.get(ontology, ontology)
        path = root / cfg.reasoner.ontology_files.get(file_key, "")
        if file_key != ontology:
            print(f"\n{ontology}: asserting into '{file_key}' ({path.name}) per arm_file_override")
        if not path or not path.exists():
            print(f"\n{ontology}: ontology file not found, skipped")
            continue
        sample = definitions[:limit]
        verdicts = _reason_over(path, sample, int(cfg.reasoner.timeout_s))
        counts = Counter(verdicts.values())
        unsat = counts["unsatisfiable"]
        scored = unsat + counts["satisfiable"]
        n_error = sum(v for k, v in counts.items() if k.startswith(("error", "setup_error")))
        low, high = clopper_pearson(unsat, scored, float(cfg.stats.conf_level))
        summary.append({
            "arm": arm, "ontology": ontology, "n_asserted": len(sample),
            "n_scored": scored, "unsatisfiable": unsat,
            "false_pass_rate": (unsat / scored) if scored else float("nan"),
            "ci_low": low, "ci_high": high,
            "errors": n_error, "inconsistent": counts["inconsistent"],
        })
        print(f"\n{ontology}: asserted={len(sample)} scored={scored} "
              f"unsat={unsat} errors={n_error}")

    out_path = out_dir / f"reasoner_{arm}.json"
    out_path.write_text(json.dumps(
        {"arm": arm, "not_translatable": dict(reasons), "results": summary}, indent=2))
    print(f"\nwritten: {out_path.relative_to(root)}")

if __name__ == "__main__":
    main()
